accounts:

  # SWOP: Verwendet einen gemeinsamen Familienaccount.
  # Vorzugsweise die Zugangsdaten des jüngeren Kindes verwenden.
  swop_family:
    username: xxx
    password: xxx

  # Drei Köche: Auf jeden Fall mit dem jüngeren Kind als child1 beginnen,
  # wenn der SWOP-Account mit dem jüngeren Kind verwendet wurde.
  drei_koeche_child1:
    username: xxx
    password: xxx

  drei_koeche_child2:
    username: xxx
    password: xxx

children:

  child1:
    swop_account: swop_family
    drei_koeche_account: drei_koeche_child1

  child2:
    swop_account: swop_family
    drei_koeche_account: drei_koeche_child2

settings:

  swop:

    fetch_range:
      weeks_past: 4
      weeks_future: 1

  drei_koeche:

    fetch_range:
      weeks_past: 12
      weeks_future: 2